image: circleci/android:api-30
  # reactnativecommunity/react-native-android

variables:
  ADB_INSTALL_TIMEOUT: 20 # Timeout for ADB installation

before_script:
  # Install pnpm globally
  - npm install -g pnpm
  # Install dependencies
  - pnpm install

stages:
  - android
  - build
  - test

android:
  stage: android
  tags:
    - android
  script:
    - echo "Setting up Android Emulator..."
    # Download and install the necessary Android SDK tools and emulator
    - sdkmanager --verbose "system-images;android-30;google_apis;x86_64"
    - sdkmanager --licenses
    - sdkmanager --verbose "platform-tools" "platforms;android-30"
    - echo "no" | avdmanager create avd -n test_avd -k "system-images;android-30;google_apis;x86_64"
    # Start the emulator in headless mode
    - nohup emulator -avd test_avd -no-snapshot -no-audio -no-window -verbose > emulator.log 2>&1 &
    # Wait for the emulator to boot
    - adb wait-for-device
    - adb shell input keyevent 82 # Unlock the emulator screen
    - echo "Emulator is ready!"

  artifacts:
    expire_in: 1 day
    # when: on_success
    paths:
      - $ANDROID_HOME
      - emulator.log

build:
  stage: build
  tags: 
    - android
  script:
    - echo "Building..."
    - pnpm android
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies: 
    - android
    - build
  script: 
    - echo "Testing..."
    - pnpm test
  
  