image: reactnativecommunity/react-native-android

variables:
  ADB_INSTALL_TIMEOUT: 10 # Timeout for ADB installation
  ANDROID_HOME: "/opt/android-sdk"
  PATH: "/opt/android-sdk/platform-tools:/opt/android-sdk/emulator:$PATH"

before_script:
  # Install pnpm globally
  - npm install -g pnpm
  # Install dependencies
  - pnpm install

stages:
  - android
  - build
  - test

android:
  stage: android
  tags:
    - android
  script:
    - echo "Setting up Android Emulator..."
    - sdkmanager "system-images;android-24;default;x86"
    - sdkmanager --licenses
    - sdkmanager "platform-tools" "platforms;android-24"
    - echo "no" | avdmanager create avd -n test_avd -k "system-images;android-24;default;x86" --device "Nexus 4"
    - nohup emulator -avd test_avd -no-window -no-audio -no-snapshot -no-boot-anim -gpu swiftshader_indirect -partition-size 1024 &
    - adb wait-for-device
    - adb shell input keyevent 82 # Unlock the emulator screen
    - echo "Emulator is ready!"

build:
  stage: build
  tags: 
    - android
  script:
    - echo "Building..."
    - pnpm android
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies: 
    - android
    - build
  script: 
    - echo "Testing..."
    - pnpm test
  
  